import { useState } from "react";
import { getMockAuthSnapshot, logoutMockAccount, deleteMockAccount } from "./mockAuth";
import { navigateBack, navigateTo } from "./navigation";

function providerName(provider?: string) { return provider === "apple" ? "Apple" : provider === "google" ? "Google" : provider === "kakao" ? "카카오" : "연결된"; }
function Header({ title, fallback = "/my-space" }: { title: string; fallback?: string }) { return <header className="flow-header"><button type="button" onClick={() => navigateBack(fallback)} aria-label="이전으로 돌아가기">←</button><strong>{title}</strong><span /></header>; }
function Dialog({ title, description, primary, onPrimary, secondary, onSecondary }: { title: string; description: string; primary: string; onPrimary: () => void; secondary: string; onSecondary: () => void }) { return <div className="auth-dialog-backdrop"><section className="auth-dialog" role="dialog" aria-modal="true" aria-labelledby="account-dialog-title"><p>계정 관리</p><h2 id="account-dialog-title">{title}</h2><span>{description}</span><button className="auth-primary" type="button" onClick={onPrimary}>{primary}</button><button className="auth-secondary" type="button" onClick={onSecondary}>{secondary}</button></section></div>; }

export function AccountSettingsScreen() {
  const account = getMockAuthSnapshot().account; const [confirmLogout, setConfirmLogout] = useState(false);
  const logout = () => { logoutMockAccount(); navigateTo("/login?notice=logged-out"); };
  const item = (title: string, detail: string, action: () => void, danger = false) => <button className={danger ? "is-danger" : ""} type="button" onClick={action}><span><strong>{title}</strong><small>{detail}</small></span><i aria-hidden="true">›</i></button>;
  return <main className="mobile-prototype account-settings-screen"><Header title="계정 관리" /><div className="my-detail-scroll"><section className="account-state-card" style={{ borderBottom: "none", paddingBottom: 0 }}><p>현재 로그인 방식</p><strong>{providerName(account?.authProvider)} 계정으로 연결됨</strong></section><section className="account-action-list" aria-label="계정 관리 메뉴">{item("로그아웃", "기록은 지우지 않고 이 기기에서만 로그아웃해요.", () => setConfirmLogout(true))}{item("회원 탈퇴", "계정 연결 해제와 보관 안내를 확인해요.", () => navigateTo("/account-withdrawal"), true)}</section></div>{confirmLogout && <Dialog title="로그아웃할까요?" description="다음에 로그인하면 이 기기의 편지를 계속 확인할 수 있어요." primary="로그아웃" onPrimary={logout} secondary="계속 이용하기" onSecondary={() => setConfirmLogout(false)} />}</main>;
}

export function LoginInformationScreen() { const account = getMockAuthSnapshot().account; const isError = new URLSearchParams(window.location.search).get("state") === "error"; return <main className="mobile-prototype account-settings-screen"><Header title="로그인 정보" fallback="/account-settings" /><div className="my-detail-scroll"><section className="subpage-heading"><h1>로그인 정보</h1><p>다른 사용자에게 공개되지 않는 로그인 방식이에요.</p></section>{isError ? <section className="account-empty-state" role="alert"><h2>로그인 정보를 불러오지 못했어요.</h2><p>잠시 후 다시 확인해주세요.</p><button className="flow-primary-button" onClick={() => navigateTo("/login-information")}>다시 시도</button></section> : <section className="account-state-card"><p>로그인 방식</p><strong>{providerName(account?.authProvider)}로 로그인했어요.</strong><span>프로토타입에서는 실제 이메일, 이름, 토큰을 조회하거나 저장하지 않아요.</span></section>}<p className="account-settings-note">TODO · 실제 서비스에서는 인증 제공자 정보와 연결 상태를 서버에서 안전하게 조회해야 해요. 로그인 방식 변경, 추가 연결, 비밀번호·이메일 수정, 계정 병합은 제공하지 않아요.</p></div></main>; }
export function DataAndPrivacyScreen() { const items = ["편지와 답장은 계정에 연결되어 보관돼요.", "작성 중인 초안은 이 기기에 잠시 남을 수 있어요.", "신고·차단 기록은 안전한 이용을 위해 보관될 수 있어요.", "탈퇴 뒤 일반 이용 데이터는 삭제 또는 비식별화 대상이에요.", "신고·분쟁·법적 의무와 관련한 일부 기록은 별도로 보관될 수 있어요."]; return <main className="mobile-prototype account-settings-screen"><Header title="데이터 보관 안내" fallback="/account-settings" /><div className="my-detail-scroll"><section className="subpage-heading"><h1>내 데이터 보관 안내</h1><p>공감편지의 기록이 어떻게 다뤄지는지 쉽게 설명해요.</p></section><section className="account-copy-list">{items.map((item) => <p key={item}>{item}</p>)}</section><p className="account-settings-note">설정·삭제·보관 기준은 실제 서비스 정책과 법률 검토 뒤 확정돼요. TODO · 최종 개인정보 처리방침 및 서버 삭제 정책을 연결해야 해요.</p></div></main>; }

const reasons = ["더 이상 이용하지 않아요", "잠시 쉬고 싶어요", "원하는 사용 방식과 달라요", "기타"];
export function AccountWithdrawalScreen() { const [step, setStep] = useState<"guide" | "reason" | "verify" | "confirm" | "processing">("guide"); const [reason, setReason] = useState(""); const [detail, setDetail] = useState(""); const [checked, setChecked] = useState(false); const [error, setError] = useState(""); const finish = () => { setStep("processing"); window.setTimeout(() => { deleteMockAccount(); navigateTo("/withdrawal-complete"); }, 900); }; if (step === "processing") return <main className="mobile-prototype account-settings-screen"><Header title="회원 탈퇴" fallback="/account-settings" /><section className="account-processing" role="status"><h1>탈퇴를 처리하고 있어요.</h1><p>이 화면을 잠시 유지해주세요.</p></section></main>; return <main className="mobile-prototype account-settings-screen"><Header title="회원 탈퇴" fallback="/account-settings" /><div className="my-detail-scroll">{step === "guide" && <><section className="subpage-heading"><h1>떠나기 전에<br />알려드릴게요</h1><p>탈퇴하면 현재 프로토타입 계정 연결만 해제돼요.</p></section><section className="account-copy-list"><p>편지, 답장, 간직한 문구와 신고·차단 기록은 개발 검수를 위해 이 기기에서 삭제하지 않아요.</p><p>초안은 처리 성공 뒤 현재 사용자 범위에서만 지워져요.</p><p>실제 서비스의 삭제·보관 기준은 정책과 법률 검토 뒤 정해져요.</p></section><button className="flow-primary-button" onClick={() => setStep("reason")}>탈퇴 계속하기</button></>}{step === "reason" && <><section className="subpage-heading"><h1>이유를 알려주실래요?</h1><p>선택하지 않아도 탈퇴할 수 있어요.</p></section><section className="withdrawal-reasons">{reasons.map((item) => <button key={item} type="button" className={reason === item ? "is-selected" : ""} onClick={() => setReason(item)}>{item}</button>)}</section>{reason === "기타" && <label className="account-textarea">추가로 남길 내용<textarea value={detail} onChange={(e) => setDetail(e.target.value)} maxLength={300} /></label>}<button className="flow-primary-button" onClick={() => setStep("verify")}>다음</button><button className="flow-text-button" onClick={() => setStep("verify")}>건너뛰기</button></>}{step === "verify" && <><section className="subpage-heading"><h1>본인 확인</h1><p>프로토타입에서는 실제 인증 대신 확인 절차를 재현해요.</p></section><label className="account-check"><input type="checkbox" checked={checked} onChange={(e) => setChecked(e.target.checked)} /> <span>탈퇴 후 계정 연결이 해제된다는 내용을 확인했어요.</span></label>{error && <p className="account-form-error" role="alert">{error}</p>}<button className="flow-primary-button" onClick={() => { if (!checked) { setError("확인 내용을 선택해주세요."); return; } setStep("confirm"); }}>확인했어요</button></>}{step === "confirm" && <><section className="subpage-heading"><h1>정말 탈퇴할까요?</h1><p>탈퇴 처리가 끝나면 현재 계정으로 서비스를 이용할 수 없어요.</p></section><section className="account-copy-list"><p>선택한 이유: {reason || "선택하지 않음"}{detail ? ` · ${detail}` : ""}</p><p>실제 서버 계정이나 개인정보는 삭제하지 않는 프로토타입 동작이에요.</p></section><button className="flow-primary-button is-danger-action" onClick={finish}>회원 탈퇴 처리하기</button><button className="flow-secondary-button" onClick={() => setStep("reason")}>취소하고 돌아가기</button></>}</div></main>; }
export function WithdrawalCompleteScreen() { return <main className="mobile-prototype account-settings-screen"><section className="account-processing"><p>계정 관리</p><h1>탈퇴 처리가<br />완료되었어요.</h1><p>이 기기의 편지와 기록은 개발 검수를 위해 보관되어 있어요.</p><button className="flow-primary-button" onClick={() => navigateTo("/intro")}>인트로로 이동하기</button></section></main>; }
export function AccountRestrictedScreen() { return <main className="mobile-prototype account-settings-screen"><Header title="계정 이용 제한" fallback="/intro" /><section className="account-processing"><h1>현재 계정의 이용이 제한되었어요.</h1><p>프로토타입 확인용 상태예요. 실제 서비스에서는 제한 사유와 문의 경로를 정책에 맞게 안내해야 해요.</p><button className="flow-primary-button" onClick={() => navigateTo("/intro")}>처음으로</button></section></main>; }
